version: '3.8'

services:
  restaurant-service:
    build: ./RestaurantService
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__RestaurantConnection=server=db;database=restaurantdb;user=root;password=root
    depends_on:
      db:
        condition: service_healthy

  item-service:
    build: ./ItemService
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=restaurantdb
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p'root'"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data: